### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dillfrescott** [gladia-research-group/multi-source-diffusion-models#3]
```
(msdm) C:\Users\micro\Downloads\multi-source-diffusion-models>python evaluate.py exp=eval_weakly_msdm_dirac
Traceback (most recent call last):
  File "C:\Users\micro\Downloads\multi-source-diffusion-models\evaluate.py", line 6, in <module>
    from main import utils
  File "C:\Users\micro\Downloads\multi-source-diffusion-models\main\utils.py", line 114, in <module>
    logger: List[pl.loggers.LightningLoggerBase],
AttributeError: module 'pytorch_lightning.loggers' has no attribute 'LightningLoggerBase'
```

**Comment by giorgio-mariani** [comment]
I believe this was caused by not having the pytorch_lightning dependency pinned in the requirements file. It should work correctly now [(fix](https://github.com/gladia-research-group/multi-source-diffusion-models/commit/a1bf393f4616160303364db1a680b4aab0ad880b)), feel free to re-open the issue if not.

**Comment by jreoka** [comment]
Gotcha. Thanks!
