### ISSUE TITLE
An error occurred when I ran evaluate.py

### ISSUE THREAD

**Issue by yeyuanzheng177** [gladia-research-group/multi-source-diffusion-models#5]
HYDRA_FULL_ERROR=1 PYTHONPATH=. python evaluate.py exp=eval_msdm_dirac
os.environ['PYTHONPATH']====================> .
Error executing job with overrides: ['exp=eval_msdm_dirac']
Traceback (most recent call last):
  File "/root/YYZ/anaconda3_10/envs/msdm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'evaluation' has no attribute 'experiments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/YYZ/anaconda3_10/envs/msdm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/root/YYZ/anaconda3_10/envs/msdm/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/yyz/code/multi-source-diffusion-models/evaluation/experiments.py", line 11, in <module>
    from main.module_base import Model
  File "/root/yyz/code/multi-source-diffusion-models/main/module_base.py", line 10, in <module>
    from pytorch_lightning.loggers import LoggerCollection, WandbLogger

**Comment by giorgio-mariani** [comment]
Thanks for letting us know, I'll look into it.

**Comment by yeyuanzheng177** [comment]
> Thanks for letting us know, I'll look into it.

Looking forward to your upcoming code submission.
